### PR TITLE
Chore/deps

### PR DESCRIPTION
**Pull request by escapedcat**
test, tsc, build working

### CODE REVIEW

**Comment by cstenglein** [comment]
Thank you :+1: 

About the typescript dependency: I'm not sure if we should update it now, since it *could* work, but will fail if we use TS >4.3 features (see https://github.com/facebook/create-react-app/issues/11022) 

Eagerly waiting for CRA 5, but until then I wouldn't wanna risk it :P

**Comment by escapedcat** [comment]
> About the typescript dependency: I'm not sure if we should update it now, since it _could_ work, but will fail if we use TS >4.3 features (see [facebook/create-react-app#11022](https://github.com/facebook/create-react-app/issues/11022))

Ah nice, was trying to find the supported version of craco. Is is mentioned in their docs somehwere?  
Will switch TS to 4.3.x, ok?

**Comment by cstenglein** [comment]
Better leave it at 4.1 :P

`craco` should work regardless, it's just that newer ts features won't be supported until cra 5

Haven't tested it yet, but I don't think there is anything breaking in it since build & test worked :)

**Comment by cstenglein** [comment]
Thx :+1:

**Pull request merged**
