### PR TITLE
chore: update deps

### PR DESCRIPTION
**Pull request by escapedcat**

### CODE REVIEW

**Comment by AaronDewes** [comment]
One issue I forgot about is that in Yarn 3, dependency updates often duplicate dependencies. After such an update, you need to run `yarn dedupe`  to avoid that. Maybe a postinstall script could help, but I'm not sure if this is run after dedupe too causing an infinite loop.

**Comment by escapedcat** [comment]
@AaronDewes thanks for the heads up. How do you notice when this happens? Do you have a link to a post/stackoverflow/GH-issue on this?  

In this PR the lock file seems to look fine, yeah?

**Comment by AaronDewes** [comment]
>  In this PR the lock file seems to look fine, yeah?

After your force push, yes. I noticed it by the logfile still including old versions of dependencies while the new version would be compatible

**Comment by AaronDewes** [comment]
Screenshot_20220109-081739

Like here (autoprefixer with the same major version in a logfile)

**Comment by escapedcat** [comment]
Is this a somehwat "known issue"?

**Comment by AaronDewes** [comment]
It's intentional behaviour AFAIK, I'll check where it's documented

**Comment by AaronDewes** [comment]
I can't find the documentation right now, but I think it was to change the least packages possible by a dependency update.

**Comment by AaronDewes** [comment]
https://dev.to/arcanis/yarn-2-2-dedupe-faster-lighter-ha5

This contains information about it

**Comment by escapedcat** [comment]
Tried to clarify the docs here: #176

**Pull request merged**
