### PR TITLE
Chore/react18

### PR DESCRIPTION
**Pull request by escapedcat**
Update React setup (incl. Jest) to v18

- ✅ i18next has type issues
- Other tests need more `act`. This seems to be a thing of React v18
- Some tests are commented out for now, because they fail, need to check what's the issue here.
  Created #234 for this

I'll try to finish this up when possible.

### CODE REVIEW

**Comment by cstenglein** [comment]
Awesome thank you! 👍

A new version of react-i18next was released which fixes that issue. :)

Currently on holiday so will look at it in a few days :)

**Comment by cstenglein** [comment]
Looked into the `act` but was only able to fix it with a workaround.

Instead of commenting out the code, could you just `xtest` them and write a `TODO` comment? Would be easier. :)

Looks like it's just the tests which are not working. App seems good :+1:

**Comment by escapedcat** [comment]
> Looked into the `act` but was only able to fix it with a workaround.
> Instead of commenting out the code, could you just `xtest` them and write a `TODO` comment? Would be easier. :)

Commenting out was left from the degbugging session. That's why the PR was marked a draft.
But yes, if we want to merge this already I can switch to `.skip` I guess and get back to fixing the tests later on.  

> Looks like it's just the tests which are not working. App seems good 👍

Ah, good to know. Couldn't really test because I didn't know how to handle new "setup"-view 😊

**Comment by cstenglein** [comment]
Yeah, my bad sorry. In the `backend-mock` it should be `DONE`, not `done`: https://github.com/cstenglein/raspiblitz-web/blob/master/backend-mock/setup.js#L10=

Then it works. Sorry for that, due to the confusion with the setup (in the other branch its `done` in lowercase).

**Comment by cstenglein** [comment]
Pushed it into master, should work now :)

**Review by cstenglein — APPROVED** [review]

**Comment by cstenglein** [comment]
Thank you very much! :) :+1:  :raised_hands:

**Pull request merged**
