### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [raspiblitz-web/translations](https://hosted.weblate.org/projects/raspiblitz-web/translations/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by escapedcat** [comment]
Pipeline fails, see: https://github.com/cstenglein/raspiblitz-web/issues/198

**Comment by escapedcat** [comment]
Solved by a re-run :P

**Comment by cstenglein** [comment]
Ok will check if it happens again :)

**Review by cstenglein — APPROVED** [review]
Thank you @moskusminer @Nom4d3 @escapedcat !

**Pull request merged**
