### PR TITLE
Provide the balance dynamically for Confirm (issue 401)

### PR DESCRIPTION
**Pull request by Yonben**
It seems to be the only thing, but I don't know your codebase like you do ;) Let me now if anything else is needed.

It's a fix for #401 :)

### CODE REVIEW

**Comment by cstenglein** [comment]
Thank you very much! Will look into it in the coming days :)

**Comment by escapedcat** [comment]
If possible would be nice to add a test for this here: https://github.com/Yonben/raspiblitz-web/blob/ISSUE-401-confirm-modal-fix/src/pages/Home/SendModal/__tests__/SendModal.test.tsx

**Comment by Yonben** [comment]
@escapedcat I added tests, thanks for highlighting that :)
@cstenglein I'm not sure I understand why the ConfirmSendModal uses both `amount` and `invoiceAmount`. The former isn't used at all but `invoiceAmount` is just a reference to `amount`. Since it supports both invoices and onchain, it seems the more generic name `amount` is a better fit here.

What do you think?

**Review by cstenglein — APPROVED** [review]

**Comment by cstenglein** [comment]
@Yonben yeah, looks like I started it sometime but didn't finish it. Just using `amount` would be the better idea here.

Anyways, the PR looks good & you even wrote tests, thank you very much :+1:

**Pull request merged**
