### PR TITLE
Migrate to Yarn 3

### PR DESCRIPTION
**Pull request by AaronDewes**
Yarn 1 isn't really receiving updates anymore, and Yarn 3 is the most recent version.

### CODE REVIEW

**Comment by cstenglein** [comment]
Thank you! :heart: 

Will most likely have time to look at it in the new Year.

**Comment by escapedcat** [comment]
Can this be fixed?:  
image

So far most of projects I'm working on haven't switched to yarn v2/3 because there were issues with other tooling we used. I read that v3 seem to have less issues with this. So if everything works like before we could give this a try.  

Wondering if https://pnpm.io would be an option as well ;)

**Review by cstenglein — CHANGES_REQUESTED** [review]
Thanks for the PR @AaronDewes ! :)

What is missing to get it running:

- https://github.com/cstenglein/raspiblitz-web/blob/master/.github/workflows/audit.yml#L26 
  - Should be `yarn npm audit --environment production` 
  - See: https://yarnpkg.com/getting-started/migration
- Most likely a `yarn install` before the audit step (looks from the error message).

**Review by escapedcat — APPROVED** [review]

**Comment by cstenglein** [comment]
@escapedcat 

> Wondering if https://pnpm.io would be an option as well ;)

Don't want to play too much with the build since it works and there is tons of other stuff to do :)

In addition the raspiblitz scripts need to be changed as well if the syntax changes, so we shouldn't change around too much :O

**Review by cstenglein — APPROVED** [review]
Thanks @AaronDewes !

**Comment by escapedcat** [comment]
> In addition the raspiblitz scripts need to be changed as well if the syntax changes, so we shouldn't change around too much :O

Just a thought. Would it be helpful to let raspiblitz call a generic `install.sh` in this repo which triggers whatever is currently needed to build this project? Might be good to decouple this.

**Comment by cstenglein** [comment]
Don't know since the tools need to be installed on the raspiblitz as well. 

I would leave it as is atm and change it if necessary.

**Pull request merged**
