### PR TITLE
refactor sidedrawer & bottomnav: navClass handling

### PR DESCRIPTION
**Pull request by escapedcat**

### CODE REVIEW

**Comment by cstenglein** [comment]
would be better to move that into the `index.css` file IMO.

Same for `BottomNav`

**Comment by escapedcat** [comment]
> would be better to move that into the `index.css` file IMO.

I just did this now but... these are not reused global classes, right? Not sure what we gain if we move this into the css-file.  
Now they are neatly placed inside the *only* component which is using them.  
What do you think?

> Same for `BottomNav`

On it.

**Comment by cstenglein** [comment]
>  Now they are neatly placed inside the only component which is using them.

Yeah you are right :D

> On it.

 :+1:

**Review by cstenglein — APPROVED** [review]
Nice, thx :+1:

**Pull request merged**
